<?php
namespace phpshko\magicscopes\tests\models;

use Yii;

use yii\db\ActiveRecord;
use phpshko\magicscopes\MagicActiveQuery;


/**
 * UserWith model
 *
 * @property integer $id
 * @property string $username
 * @property string $forename
 * @property string $surname
 * @property integer $year
 * @property integer $address_id
 *
 * Magic Scopes
 *
 * @method MagicActiveQuery|UserWith id($id)
 * @method MagicActiveQuery|UserWith idIn($array)
 * @method MagicActiveQuery|UserWith idLike($id)
 * @method MagicActiveQuery|UserWith idBetween($from, $to)
 * @method MagicActiveQuery|UserWith idMore($than, $include = false)
 * @method MagicActiveQuery|UserWith idLess($than, $include = false)
 * @method MagicActiveQuery|UserWith idNot($id)
 * @method MagicActiveQuery|UserWith idNotIn($array)
 * @method MagicActiveQuery|UserWith idNotLike($id)
 * @method MagicActiveQuery|UserWith idNotBetween($from, $to)
 * @method MagicActiveQuery|UserWith idNotMore($than, $include = false)
 * @method MagicActiveQuery|UserWith idNotLess($than, $include = false)
 * @method MagicActiveQuery|UserWith andId($id)
 * @method MagicActiveQuery|UserWith andIdIn($array)
 * @method MagicActiveQuery|UserWith andIdLike($id)
 * @method MagicActiveQuery|UserWith andIdBetween($from, $to)
 * @method MagicActiveQuery|UserWith andIdMore($than, $include = false)
 * @method MagicActiveQuery|UserWith andIdLess($than, $include = false)
 * @method MagicActiveQuery|UserWith andIdNot($id)
 * @method MagicActiveQuery|UserWith andIdNotIn($array)
 * @method MagicActiveQuery|UserWith andIdNotLike($id)
 * @method MagicActiveQuery|UserWith andIdNotBetween($from, $to)
 * @method MagicActiveQuery|UserWith andIdNotMore($than, $include = false)
 * @method MagicActiveQuery|UserWith andIdNotLess($than, $include = false)
 * @method MagicActiveQuery|UserWith orIdIn($array)
 * @method MagicActiveQuery|UserWith orIdLike($id)
 * @method MagicActiveQuery|UserWith orIdBetween($from, $to)
 * @method MagicActiveQuery|UserWith orIdMore($than, $include = false)
 * @method MagicActiveQuery|UserWith orIdLess($than, $include = false)
 * @method MagicActiveQuery|UserWith orIdNot($id)
 * @method MagicActiveQuery|UserWith orIdNotIn($array)
 * @method MagicActiveQuery|UserWith orIdNotLike($id)
 * @method MagicActiveQuery|UserWith orIdNotBetween($from, $to)
 * @method MagicActiveQuery|UserWith orIdNotMore($than, $include = false)
 * @method MagicActiveQuery|UserWith orIdNotLess($than, $include = false)
 * @method MagicActiveQuery|UserWith orId($id)
 *
 * @method MagicActiveQuery|UserWith username($username)
 * @method MagicActiveQuery|UserWith usernameIn($array)
 * @method MagicActiveQuery|UserWith usernameLike($username)
 * @method MagicActiveQuery|UserWith usernameBetween($from, $to)
 * @method MagicActiveQuery|UserWith usernameMore($than, $include = false)
 * @method MagicActiveQuery|UserWith usernameLess($than, $include = false)
 * @method MagicActiveQuery|UserWith usernameNot($username)
 * @method MagicActiveQuery|UserWith usernameNotIn($array)
 * @method MagicActiveQuery|UserWith usernameNotLike($username)
 * @method MagicActiveQuery|UserWith usernameNotBetween($from, $to)
 * @method MagicActiveQuery|UserWith usernameNotMore($than, $include = false)
 * @method MagicActiveQuery|UserWith usernameNotLess($than, $include = false)
 * @method MagicActiveQuery|UserWith andUsername($username)
 * @method MagicActiveQuery|UserWith andUsernameIn($array)
 * @method MagicActiveQuery|UserWith andUsernameLike($username)
 * @method MagicActiveQuery|UserWith andUsernameBetween($from, $to)
 * @method MagicActiveQuery|UserWith andUsernameMore($than, $include = false)
 * @method MagicActiveQuery|UserWith andUsernameLess($than, $include = false)
 * @method MagicActiveQuery|UserWith andUsernameNot($username)
 * @method MagicActiveQuery|UserWith andUsernameNotIn($array)
 * @method MagicActiveQuery|UserWith andUsernameNotLike($username)
 * @method MagicActiveQuery|UserWith andUsernameNotBetween($from, $to)
 * @method MagicActiveQuery|UserWith andUsernameNotMore($than, $include = false)
 * @method MagicActiveQuery|UserWith andUsernameNotLess($than, $include = false)
 * @method MagicActiveQuery|UserWith orUsernameIn($array)
 * @method MagicActiveQuery|UserWith orUsernameLike($username)
 * @method MagicActiveQuery|UserWith orUsernameBetween($from, $to)
 * @method MagicActiveQuery|UserWith orUsernameMore($than, $include = false)
 * @method MagicActiveQuery|UserWith orUsernameLess($than, $include = false)
 * @method MagicActiveQuery|UserWith orUsernameNot($username)
 * @method MagicActiveQuery|UserWith orUsernameNotIn($array)
 * @method MagicActiveQuery|UserWith orUsernameNotLike($username)
 * @method MagicActiveQuery|UserWith orUsernameNotBetween($from, $to)
 * @method MagicActiveQuery|UserWith orUsernameNotMore($than, $include = false)
 * @method MagicActiveQuery|UserWith orUsernameNotLess($than, $include = false)
 * @method MagicActiveQuery|UserWith orUsername($username)
 *
 * @method MagicActiveQuery|UserWith forename($forename)
 * @method MagicActiveQuery|UserWith forenameIn($array)
 * @method MagicActiveQuery|UserWith forenameLike($forename)
 * @method MagicActiveQuery|UserWith forenameBetween($from, $to)
 * @method MagicActiveQuery|UserWith forenameMore($than, $include = false)
 * @method MagicActiveQuery|UserWith forenameLess($than, $include = false)
 * @method MagicActiveQuery|UserWith forenameNot($forename)
 * @method MagicActiveQuery|UserWith forenameNotIn($array)
 * @method MagicActiveQuery|UserWith forenameNotLike($forename)
 * @method MagicActiveQuery|UserWith forenameNotBetween($from, $to)
 * @method MagicActiveQuery|UserWith forenameNotMore($than, $include = false)
 * @method MagicActiveQuery|UserWith forenameNotLess($than, $include = false)
 * @method MagicActiveQuery|UserWith andForename($forename)
 * @method MagicActiveQuery|UserWith andForenameIn($array)
 * @method MagicActiveQuery|UserWith andForenameLike($forename)
 * @method MagicActiveQuery|UserWith andForenameBetween($from, $to)
 * @method MagicActiveQuery|UserWith andForenameMore($than, $include = false)
 * @method MagicActiveQuery|UserWith andForenameLess($than, $include = false)
 * @method MagicActiveQuery|UserWith andForenameNot($forename)
 * @method MagicActiveQuery|UserWith andForenameNotIn($array)
 * @method MagicActiveQuery|UserWith andForenameNotLike($forename)
 * @method MagicActiveQuery|UserWith andForenameNotBetween($from, $to)
 * @method MagicActiveQuery|UserWith andForenameNotMore($than, $include = false)
 * @method MagicActiveQuery|UserWith andForenameNotLess($than, $include = false)
 * @method MagicActiveQuery|UserWith orForenameIn($array)
 * @method MagicActiveQuery|UserWith orForenameLike($forename)
 * @method MagicActiveQuery|UserWith orForenameBetween($from, $to)
 * @method MagicActiveQuery|UserWith orForenameMore($than, $include = false)
 * @method MagicActiveQuery|UserWith orForenameLess($than, $include = false)
 * @method MagicActiveQuery|UserWith orForenameNot($forename)
 * @method MagicActiveQuery|UserWith orForenameNotIn($array)
 * @method MagicActiveQuery|UserWith orForenameNotLike($forename)
 * @method MagicActiveQuery|UserWith orForenameNotBetween($from, $to)
 * @method MagicActiveQuery|UserWith orForenameNotMore($than, $include = false)
 * @method MagicActiveQuery|UserWith orForenameNotLess($than, $include = false)
 * @method MagicActiveQuery|UserWith orForename($forename)
 *
 * @method MagicActiveQuery|UserWith surname($surname)
 * @method MagicActiveQuery|UserWith surnameIn($array)
 * @method MagicActiveQuery|UserWith surnameLike($surname)
 * @method MagicActiveQuery|UserWith surnameBetween($from, $to)
 * @method MagicActiveQuery|UserWith surnameMore($than, $include = false)
 * @method MagicActiveQuery|UserWith surnameLess($than, $include = false)
 * @method MagicActiveQuery|UserWith surnameNot($surname)
 * @method MagicActiveQuery|UserWith surnameNotIn($array)
 * @method MagicActiveQuery|UserWith surnameNotLike($surname)
 * @method MagicActiveQuery|UserWith surnameNotBetween($from, $to)
 * @method MagicActiveQuery|UserWith surnameNotMore($than, $include = false)
 * @method MagicActiveQuery|UserWith surnameNotLess($than, $include = false)
 * @method MagicActiveQuery|UserWith andSurname($surname)
 * @method MagicActiveQuery|UserWith andSurnameIn($array)
 * @method MagicActiveQuery|UserWith andSurnameLike($surname)
 * @method MagicActiveQuery|UserWith andSurnameBetween($from, $to)
 * @method MagicActiveQuery|UserWith andSurnameMore($than, $include = false)
 * @method MagicActiveQuery|UserWith andSurnameLess($than, $include = false)
 * @method MagicActiveQuery|UserWith andSurnameNot($surname)
 * @method MagicActiveQuery|UserWith andSurnameNotIn($array)
 * @method MagicActiveQuery|UserWith andSurnameNotLike($surname)
 * @method MagicActiveQuery|UserWith andSurnameNotBetween($from, $to)
 * @method MagicActiveQuery|UserWith andSurnameNotMore($than, $include = false)
 * @method MagicActiveQuery|UserWith andSurnameNotLess($than, $include = false)
 * @method MagicActiveQuery|UserWith orSurnameIn($array)
 * @method MagicActiveQuery|UserWith orSurnameLike($surname)
 * @method MagicActiveQuery|UserWith orSurnameBetween($from, $to)
 * @method MagicActiveQuery|UserWith orSurnameMore($than, $include = false)
 * @method MagicActiveQuery|UserWith orSurnameLess($than, $include = false)
 * @method MagicActiveQuery|UserWith orSurnameNot($surname)
 * @method MagicActiveQuery|UserWith orSurnameNotIn($array)
 * @method MagicActiveQuery|UserWith orSurnameNotLike($surname)
 * @method MagicActiveQuery|UserWith orSurnameNotBetween($from, $to)
 * @method MagicActiveQuery|UserWith orSurnameNotMore($than, $include = false)
 * @method MagicActiveQuery|UserWith orSurnameNotLess($than, $include = false)
 * @method MagicActiveQuery|UserWith orSurname($surname)
 *
 * @method MagicActiveQuery|UserWith year($year)
 * @method MagicActiveQuery|UserWith yearIn($array)
 * @method MagicActiveQuery|UserWith yearLike($year)
 * @method MagicActiveQuery|UserWith yearBetween($from, $to)
 * @method MagicActiveQuery|UserWith yearMore($than, $include = false)
 * @method MagicActiveQuery|UserWith yearLess($than, $include = false)
 * @method MagicActiveQuery|UserWith yearNot($year)
 * @method MagicActiveQuery|UserWith yearNotIn($array)
 * @method MagicActiveQuery|UserWith yearNotLike($year)
 * @method MagicActiveQuery|UserWith yearNotBetween($from, $to)
 * @method MagicActiveQuery|UserWith yearNotMore($than, $include = false)
 * @method MagicActiveQuery|UserWith yearNotLess($than, $include = false)
 * @method MagicActiveQuery|UserWith andYear($year)
 * @method MagicActiveQuery|UserWith andYearIn($array)
 * @method MagicActiveQuery|UserWith andYearLike($year)
 * @method MagicActiveQuery|UserWith andYearBetween($from, $to)
 * @method MagicActiveQuery|UserWith andYearMore($than, $include = false)
 * @method MagicActiveQuery|UserWith andYearLess($than, $include = false)
 * @method MagicActiveQuery|UserWith andYearNot($year)
 * @method MagicActiveQuery|UserWith andYearNotIn($array)
 * @method MagicActiveQuery|UserWith andYearNotLike($year)
 * @method MagicActiveQuery|UserWith andYearNotBetween($from, $to)
 * @method MagicActiveQuery|UserWith andYearNotMore($than, $include = false)
 * @method MagicActiveQuery|UserWith andYearNotLess($than, $include = false)
 * @method MagicActiveQuery|UserWith orYearIn($array)
 * @method MagicActiveQuery|UserWith orYearLike($year)
 * @method MagicActiveQuery|UserWith orYearBetween($from, $to)
 * @method MagicActiveQuery|UserWith orYearMore($than, $include = false)
 * @method MagicActiveQuery|UserWith orYearLess($than, $include = false)
 * @method MagicActiveQuery|UserWith orYearNot($year)
 * @method MagicActiveQuery|UserWith orYearNotIn($array)
 * @method MagicActiveQuery|UserWith orYearNotLike($year)
 * @method MagicActiveQuery|UserWith orYearNotBetween($from, $to)
 * @method MagicActiveQuery|UserWith orYearNotMore($than, $include = false)
 * @method MagicActiveQuery|UserWith orYearNotLess($than, $include = false)
 * @method MagicActiveQuery|UserWith orYear($year)
 *
 * @method MagicActiveQuery|UserWith addressId($addressId)
 * @method MagicActiveQuery|UserWith addressIdIn($array)
 * @method MagicActiveQuery|UserWith addressIdLike($addressId)
 * @method MagicActiveQuery|UserWith addressIdBetween($from, $to)
 * @method MagicActiveQuery|UserWith addressIdMore($than, $include = false)
 * @method MagicActiveQuery|UserWith addressIdLess($than, $include = false)
 * @method MagicActiveQuery|UserWith addressIdNot($addressId)
 * @method MagicActiveQuery|UserWith addressIdNotIn($array)
 * @method MagicActiveQuery|UserWith addressIdNotLike($addressId)
 * @method MagicActiveQuery|UserWith addressIdNotBetween($from, $to)
 * @method MagicActiveQuery|UserWith addressIdNotMore($than, $include = false)
 * @method MagicActiveQuery|UserWith addressIdNotLess($than, $include = false)
 * @method MagicActiveQuery|UserWith andAddressId($addressId)
 * @method MagicActiveQuery|UserWith andAddressIdIn($array)
 * @method MagicActiveQuery|UserWith andAddressIdLike($addressId)
 * @method MagicActiveQuery|UserWith andAddressIdBetween($from, $to)
 * @method MagicActiveQuery|UserWith andAddressIdMore($than, $include = false)
 * @method MagicActiveQuery|UserWith andAddressIdLess($than, $include = false)
 * @method MagicActiveQuery|UserWith andAddressIdNot($addressId)
 * @method MagicActiveQuery|UserWith andAddressIdNotIn($array)
 * @method MagicActiveQuery|UserWith andAddressIdNotLike($addressId)
 * @method MagicActiveQuery|UserWith andAddressIdNotBetween($from, $to)
 * @method MagicActiveQuery|UserWith andAddressIdNotMore($than, $include = false)
 * @method MagicActiveQuery|UserWith andAddressIdNotLess($than, $include = false)
 * @method MagicActiveQuery|UserWith orAddressIdIn($array)
 * @method MagicActiveQuery|UserWith orAddressIdLike($addressId)
 * @method MagicActiveQuery|UserWith orAddressIdBetween($from, $to)
 * @method MagicActiveQuery|UserWith orAddressIdMore($than, $include = false)
 * @method MagicActiveQuery|UserWith orAddressIdLess($than, $include = false)
 * @method MagicActiveQuery|UserWith orAddressIdNot($addressId)
 * @method MagicActiveQuery|UserWith orAddressIdNotIn($array)
 * @method MagicActiveQuery|UserWith orAddressIdNotLike($addressId)
 * @method MagicActiveQuery|UserWith orAddressIdNotBetween($from, $to)
 * @method MagicActiveQuery|UserWith orAddressIdNotMore($than, $include = false)
 * @method MagicActiveQuery|UserWith orAddressIdNotLess($than, $include = false)
 * @method MagicActiveQuery|UserWith orAddressId($addressId)
 *
 */
class UserWith extends ActiveRecord
{
    /**
     * @inheritdoc
     * @return MagicActiveQuery|UserWith
     */
    public static function find()
    {
        return new MagicActiveQuery(get_called_class());
    }


    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'user';
    }
}
